
// job vacancy action types
export const JOB_VACANCY_FETCH_ALL = "JOB_VACANCY/FETCH_ALL";
export const JOB_VACANCY_ADD_JOB = "JOB_VACANCY/ADD_JOB";
export const JOB_VACANCY_FETCH_BY_ID = "JOB_VACANCY/FETCH_BY_ID";
export const JOB_VACANCY_UPDATE_JOB = "JOB_VACANCY/UPDATE_JOB";